### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by shiruken1** [randing89/ngrequire-webpack-plugin#4]
Hello there and thank you for writing this plugin! I'm really excited to try it out.

I included the requirement in my webpack.config file, and got the following error:

```
Error: Cannot find module 'webpack/lib/ModuleParserHelpers'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (.../node_modules/ngrequire-webpack-plugin/index.js:1:89)
```

Thanks in advance for your help!

**Comment by randing89** [comment]
Hi. I haven't been maintaining this plugin to keep up with the latest version of webpack for quite a while for various reasons. PRs are welcome :)

Thanks
